# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/XDC/ZYBO_Master.xdc

# Block Designs: bd/ccc_design/ccc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design || ORIG_REF_NAME==ccc_design}]

# IP: bd/ccc_design/ip/ccc_design_processing_system7_0_0/ccc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_processing_system7_0_0 || ORIG_REF_NAME==ccc_design_processing_system7_0_0}]

# IP: bd/ccc_design/ip/ccc_design_processing_system7_0_axi_periph_0/ccc_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==ccc_design_processing_system7_0_axi_periph_0}]

# IP: bd/ccc_design/ip/ccc_design_rst_processing_system7_0_100M_0/ccc_design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ccc_design_rst_processing_system7_0_100M_0}]

# IP: bd/ccc_design/ip/ccc_design_xbar_0/ccc_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_xbar_0 || ORIG_REF_NAME==ccc_design_xbar_0}]

# IP: bd/ccc_design/ip/ccc_design_axi_gpio_0_1/ccc_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_1 || ORIG_REF_NAME==ccc_design_axi_gpio_0_1}]

# IP: bd/ccc_design/ip/ccc_design_ESPI_0_0/ccc_design_ESPI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_ESPI_0_0 || ORIG_REF_NAME==ccc_design_ESPI_0_0}]

# IP: bd/ccc_design/ip/ccc_design_axi_timer_0_0/ccc_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_timer_0_0 || ORIG_REF_NAME==ccc_design_axi_timer_0_0}]

# IP: bd/ccc_design/ip/ccc_design_axi_timer_1_0/ccc_design_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_timer_1_0 || ORIG_REF_NAME==ccc_design_axi_timer_1_0}]

# IP: bd/ccc_design/ip/ccc_design_axi_gpio_0_0/ccc_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_0 || ORIG_REF_NAME==ccc_design_axi_gpio_0_0}]

# IP: bd/ccc_design/ip/ccc_design_auto_pc_0/ccc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_auto_pc_0 || ORIG_REF_NAME==ccc_design_auto_pc_0}]

# XDC: bd/ccc_design/ip/ccc_design_processing_system7_0_0/ccc_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ccc_design_processing_system7_0_0 || ORIG_REF_NAME==ccc_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ccc_design/ip/ccc_design_rst_processing_system7_0_100M_0/ccc_design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ccc_design_rst_processing_system7_0_100M_0}]

# XDC: bd/ccc_design/ip/ccc_design_rst_processing_system7_0_100M_0/ccc_design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ccc_design_rst_processing_system7_0_100M_0}]

# XDC: bd/ccc_design/ip/ccc_design_rst_processing_system7_0_100M_0/ccc_design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_xbar_0/ccc_design_xbar_0_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_1/ccc_design_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_1 || ORIG_REF_NAME==ccc_design_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_1/ccc_design_axi_gpio_0_1_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_1/ccc_design_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_1 || ORIG_REF_NAME==ccc_design_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/ccc_design/ip/ccc_design_axi_timer_0_0/ccc_design_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_timer_0_0 || ORIG_REF_NAME==ccc_design_axi_timer_0_0}]

# XDC: bd/ccc_design/ip/ccc_design_axi_timer_0_0/ccc_design_axi_timer_0_0_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_axi_timer_1_0/ccc_design_axi_timer_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ccc_design_axi_timer_1_0 || ORIG_REF_NAME==ccc_design_axi_timer_1_0}]

# XDC: bd/ccc_design/ip/ccc_design_axi_timer_1_0/ccc_design_axi_timer_1_0_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_0/ccc_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_0 || ORIG_REF_NAME==ccc_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_0/ccc_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/ccc_design/ip/ccc_design_axi_gpio_0_0/ccc_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ccc_design_axi_gpio_0_0 || ORIG_REF_NAME==ccc_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ccc_design/ip/ccc_design_auto_pc_0/ccc_design_auto_pc_0_ooc.xdc

# XDC: bd/ccc_design/ccc_design_ooc.xdc
